# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-09 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stores',
            new_name='Store',
        ),
        migrations.RenameField(
            model_name='modal',
            old_name='modal_text_id',
            new_name='modal_text_settings',
        ),
        migrations.RenameField(
            model_name='modal',
            old_name='store_name',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='store_name',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='store_name',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='productviews',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productviews',
            old_name='store_name',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='storesettings',
            old_name='store_name',
            new_name='store',
        ),
        migrations.AlterUniqueTogether(
            name='modal',
            unique_together=set([('store', 'modal_text_settings')]),
        ),
        migrations.AlterUniqueTogether(
            name='orders',
            unique_together=set([('store', 'product', 'order_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set([('store', 'product_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='productviews',
            unique_together=set([('store', 'product')]),
        ),
    ]
