# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-09 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171109_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
